name: ServerAdditions
version: '${project.version}'
main: dev.conah.serveradditions.ServerAdditions
api-version: '1.16'
authors: [ ConaII_ ]
website: https://github.com/ConaII
description: 'Adds useful things to customize and decorate your server!'

commands:
  save:
    description: Fancy save for your server!
    aliases: se_save

  se_restart:
    description: Fancy restart for your server!

permissions:
  serveradditions.save:
    default: op

  serveradditions.save-flush:
    default: op

  serveradditions.save-on:
    default: op

  serveradditions.save.off:
    default: op

  serveradditions.receive.global:
    default: true

  serveradditions.receive.admin:
    default: op

  serveradditions.receive.silent:
    default: op